import { ShortcutApp } from "./types"

export const shortcutsData: ShortcutApp[] = [
  {
    name: "Chrome",
    icon: "🌐",
    shortcuts: [
      { keys: ["Cmd", "T"], description: "新しいタブを開く", category: "タブ操作" },
      { keys: ["Cmd", "W"], description: "タブを閉じる", category: "タブ操作" },
      { keys: ["Cmd", "Shift", "T"], description: "閉じたタブを再度開く", category: "タブ操作" },
      { keys: ["Cmd", "1~8"], description: "特定のタブに移動", category: "タブ操作" },
      { keys: ["Cmd", "9"], description: "最後のタブに移動", category: "タブ操作" },
      { keys: ["Ctrl", "Tab"], description: "次のタブに移動", category: "タブ操作" },
      { keys: ["Ctrl", "Shift", "Tab"], description: "前のタブに移動", category: "タブ操作" },
      { keys: ["Cmd", "L"], description: "アドレスバーにフォーカス", category: "ナビゲーション" },
      { keys: ["Cmd", "R"], description: "ページを再読み込み", category: "ナビゲーション" },
      { keys: ["Cmd", "Shift", "R"], description: "キャッシュクリアして再読み込み", category: "ナビゲーション" },
      { keys: ["Cmd", "["], description: "戻る", category: "ナビゲーション" },
      { keys: ["Cmd", "]"], description: "進む", category: "ナビゲーション" },
      { keys: ["Cmd", "F"], description: "ページ内検索", category: "検索" },
      { keys: ["Cmd", "G"], description: "次の検索結果", category: "検索" },
      { keys: ["Cmd", "Shift", "G"], description: "前の検索結果", category: "検索" },
      { keys: ["Cmd", "D"], description: "ブックマークに追加", category: "ブックマーク" },
      { keys: ["Cmd", "Shift", "B"], description: "ブックマークバー表示切替", category: "ブックマーク" },
      { keys: ["Cmd", "Option", "I"], description: "デベロッパーツールを開く", category: "開発者向け" },
      { keys: ["Cmd", "Shift", "Delete"], description: "閲覧履歴データを削除", category: "その他" },
      { keys: ["Cmd", "Shift", "N"], description: "シークレットウィンドウを開く", category: "その他" },
    ],
  },
  {
    name: "YouTube",
    icon: "▶️",
    shortcuts: [
      { keys: ["Space"], description: "再生/一時停止", category: "再生操作" },
      { keys: ["K"], description: "再生/一時停止", category: "再生操作" },
      { keys: ["J"], description: "10秒戻る", category: "再生操作" },
      { keys: ["L"], description: "10秒進む", category: "再生操作" },
      { keys: ["←"], description: "5秒戻る", category: "再生操作" },
      { keys: ["→"], description: "5秒進む", category: "再生操作" },
      { keys: ["↑"], description: "音量を上げる", category: "音量操作" },
      { keys: ["↓"], description: "音量を下げる", category: "音量操作" },
      { keys: ["M"], description: "ミュート切替", category: "音量操作" },
      { keys: ["F"], description: "フルスクリーン切替", category: "表示操作" },
      { keys: ["T"], description: "シアターモード切替", category: "表示操作" },
      { keys: ["I"], description: "ミニプレーヤー", category: "表示操作" },
      { keys: ["C"], description: "字幕のオン/オフ", category: "表示操作" },
      { keys: ["0~9"], description: "動画の0%~90%の位置に移動", category: "シーク" },
      { keys: ["Home"], description: "動画の先頭に移動", category: "シーク" },
      { keys: ["End"], description: "動画の最後に移動", category: "シーク" },
      { keys: [">"], description: "再生速度を上げる", category: "再生速度" },
      { keys: ["<"], description: "再生速度を下げる", category: "再生速度" },
      { keys: ["/"], description: "検索ボックスにフォーカス", category: "ナビゲーション" },
    ],
  },
  {
    name: "VS Code",
    icon: "💻",
    shortcuts: [
      { keys: ["Cmd", "P"], description: "ファイルを開く", category: "ファイル操作" },
      { keys: ["Cmd", "Shift", "P"], description: "コマンドパレット", category: "コマンド" },
      { keys: ["Cmd", "N"], description: "新しいファイル", category: "ファイル操作" },
      { keys: ["Cmd", "S"], description: "保存", category: "ファイル操作" },
      { keys: ["Cmd", "Shift", "S"], description: "名前を付けて保存", category: "ファイル操作" },
      { keys: ["Cmd", "W"], description: "エディタを閉じる", category: "ファイル操作" },
      { keys: ["Cmd", "K", "Cmd", "W"], description: "全てのエディタを閉じる", category: "ファイル操作" },
      { keys: ["Cmd", "F"], description: "検索", category: "検索・置換" },
      { keys: ["Cmd", "Shift", "F"], description: "ワークスペース内検索", category: "検索・置換" },
      { keys: ["Cmd", "H"], description: "置換", category: "検索・置換" },
      { keys: ["Cmd", "Shift", "H"], description: "ワークスペース内置換", category: "検索・置換" },
      { keys: ["Cmd", "/"], description: "行コメント切替", category: "編集" },
      { keys: ["Cmd", "Shift", "A"], description: "ブロックコメント切替", category: "編集" },
      { keys: ["Cmd", "D"], description: "次の一致を選択", category: "選択" },
      { keys: ["Cmd", "Shift", "L"], description: "全ての一致を選択", category: "選択" },
      { keys: ["Option", "↑"], description: "行を上に移動", category: "編集" },
      { keys: ["Option", "↓"], description: "行を下に移動", category: "編集" },
      { keys: ["Shift", "Option", "↑"], description: "行を上にコピー", category: "編集" },
      { keys: ["Shift", "Option", "↓"], description: "行を下にコピー", category: "編集" },
      { keys: ["Cmd", "Shift", "K"], description: "行を削除", category: "編集" },
      { keys: ["Cmd", "Enter"], description: "下に行を挿入", category: "編集" },
      { keys: ["Cmd", "Shift", "Enter"], description: "上に行を挿入", category: "編集" },
      { keys: ["Cmd", "B"], description: "サイドバー表示切替", category: "表示" },
      { keys: ["Cmd", "J"], description: "パネル表示切替", category: "表示" },
      { keys: ["Cmd", "`"], description: "ターミナル表示切替", category: "表示" },
      { keys: ["Cmd", "Shift", "E"], description: "エクスプローラーにフォーカス", category: "ナビゲーション" },
      { keys: ["Cmd", "Shift", "X"], description: "拡張機能", category: "ナビゲーション" },
      { keys: ["Cmd", "Shift", "D"], description: "デバッグビュー", category: "ナビゲーション" },
      { keys: ["F5"], description: "デバッグ開始/続行", category: "デバッグ" },
      { keys: ["F9"], description: "ブレークポイント切替", category: "デバッグ" },
      { keys: ["F10"], description: "ステップオーバー", category: "デバッグ" },
      { keys: ["F11"], description: "ステップイン", category: "デバッグ" },
      { keys: ["Shift", "F11"], description: "ステップアウト", category: "デバッグ" },
    ],
  },
  {
    name: "PixAI",
    icon: "🎨",
    shortcuts: [
      { keys: ["Space"], description: "画像の拡大/縮小切替", category: "表示操作" },
      { keys: ["Ctrl", "Enter"], description: "生成開始", category: "生成操作" },
      { keys: ["Ctrl", "Z"], description: "元に戻す", category: "編集" },
      { keys: ["Ctrl", "Y"], description: "やり直す", category: "編集" },
      { keys: ["Ctrl", "S"], description: "保存", category: "ファイル操作" },
      { keys: ["Ctrl", "C"], description: "コピー", category: "編集" },
      { keys: ["Ctrl", "V"], description: "貼り付け", category: "編集" },
      { keys: ["Delete"], description: "削除", category: "編集" },
      { keys: ["Ctrl", "D"], description: "複製", category: "編集" },
      { keys: ["Esc"], description: "選択解除/キャンセル", category: "ナビゲーション" },
      { keys: ["Tab"], description: "次の要素にフォーカス", category: "ナビゲーション" },
      { keys: ["Shift", "Tab"], description: "前の要素にフォーカス", category: "ナビゲーション" },
      { keys: ["Ctrl", "+"], description: "ズームイン", category: "表示操作" },
      { keys: ["Ctrl", "-"], description: "ズームアウト", category: "表示操作" },
      { keys: ["Ctrl", "0"], description: "100%表示", category: "表示操作" },
      { keys: ["F"], description: "フルスクリーン切替", category: "表示操作" },
      { keys: ["G"], description: "グリッド表示切替", category: "表示操作" },
      { keys: ["R"], description: "定規表示切替", category: "表示操作" },
    ],
  },
]
